import React, { useState } from 'react';
import OmrSheetGenerator from './components/OmrSheetGenerator';
import OmrSheetReader from './components/OmrSheetReader';
import { GenerateIcon, ScanIcon } from './components/icons';

type View = 'generator' | 'reader';

const App: React.FC = () => {
  const [activeView, setActiveView] = useState<View>('generator');

  const renderView = () => {
    switch (activeView) {
      case 'generator':
        return <OmrSheetGenerator />;
      case 'reader':
        return <OmrSheetReader />;
      default:
        return <OmrSheetGenerator />;
    }
  };

  // FIX: Changed `JSX.Element` to `React.ReactNode` to fix "Cannot find namespace 'JSX'" error.
  const TabButton = ({ view, label, icon }: { view: View; label: string; icon: React.ReactNode }) => (
    <button
      onClick={() => setActiveView(view)}
      className={`flex items-center justify-center gap-2 px-4 py-3 text-sm font-semibold transition-all duration-200 rounded-lg ${
        activeView === view
          ? 'bg-blue-600 text-white shadow-md'
          : 'bg-white text-gray-700 hover:bg-gray-200'
      }`}
    >
      {icon}
      {label}
    </button>
  );

  return (
    <div className="min-h-screen bg-gray-50 flex flex-col items-center p-4 sm:p-6 lg:p-8">
      <div className="w-full max-w-7xl mx-auto">
        <header className="text-center mb-8">
          <h1 className="text-4xl font-extrabold text-gray-800 tracking-tight sm:text-5xl">
            Smart OMR Generator & Reader
          </h1>
          <p className="mt-3 max-w-2xl mx-auto text-lg text-gray-500">
            Create, print, and grade optical mark recognition sheets with ease.
          </p>
        </header>

        <main className="bg-white rounded-2xl shadow-lg p-4 sm:p-8">
          <div className="flex justify-center mb-8 p-2 bg-gray-100 rounded-xl max-w-md mx-auto">
            <TabButton view="generator" label="Generate Sheet" icon={<GenerateIcon />} />
            <TabButton view="reader" label="Scan & Grade" icon={<ScanIcon />} />
          </div>
          {renderView()}
        </main>

        <footer className="text-center py-8 text-gray-500 text-sm">
          <p>Generated by Toufiq Hasan • Smart OMR Generator</p>
        </footer>
      </div>
    </div>
  );
};

export default App;
